language: node_js
node_js:
 - 8.10.0
services:
 - postgresql

os:
 - linux
 - windows

jobs:
  allow_failures:
   - os: windows

cache:
 - npm

before_script:
 - npm run gulp
 - node bin/setup_db.js | psql -U postgres
 - mkdir certs
 - openssl req -x509 -newkey rsa:4096 -keyout certs/lt.key -out certs/lt.pem -nodes -subj '/CN=localhost' -days 365
 
script:
 - npm run test

after_script:
 - npm run coverage
