language: node_js
node_js:
 - 10.17.0
services:
 - postgresql
os:
 - linux
 - windows

matrix:
  allow_failures:
   - os: windows
  fast_finish: true

cache:
 - npm

before_script:
 - if [ "$TRAVIS_OS_NAME" = "windows" ]; then choco install postgresql; fi
 - npm run gulp
 - node bin/setup_db.js | psql -U postgres
 - mkdir certs
 - openssl req -x509 -newkey rsa:4096 -keyout certs/lt.key -out certs/lt.pem -nodes -subj '/CN=localhost' -days 365
 
script:
 - npm run test

after_script:
 - npm run coverage

notifications:
  email:
    recipients:
     - secure: "jMZAOxE+ARvqaSgKwloZM59lVe8ncxLJHpVYYvpk2CjBi+irP/VpSlraUwwE2Jb8zEFRSYDD9daRCeiBxsGTG5W409sPvs/u2PVyVtrqUBhOKCYBriXsdX5AlLJ/WJJcVQVm8XMgfX4YHmIMdYjdzAdZ2NW6ZwWwFOQsbdLH85qO0oLjMSoPwNAoriV9oxnBVjDIuwIto+RFxBEBWDNXoryQlBXl5fmFY3Uo+LB7EZylQ1sVY4o/ST1oPdwdbQhKbbnJDYzflQi4zNLWfcKVSjmi8y5WitXSOhEj8xVFgOWZzqJSB7QHhzSVHuClH1xCcOGi06zwWHYR8bueU1JuOj5QiG1rqXn4RFgGdWUGwgWdm+xylU19jkNjJ7tk65oHYzlBF7AaN5a2eXxYBGFIO/pktMyjDsIw1Ui/RSS0HEGuIr6Zhgo/hRN6aOyqZL1AolxyTMA8ODzosWQolacMVoYcw1nVMOEX9KhTjTfLVDCLZvbqgyZQOezBEyyv1+LqO4gxmPkK38dRix7jzZvBmo/nD0uY2ytbISEE8ctu4EpTXbI2HiDPL6Y+0QogchRM0cyljSTrU4Ug+AbBVTgwgkF+ofp1L8IhTyguvFclU7G7iYCoisNHFP43X/D+T4lrIyXTGUJmS1++g/MPtYimylJH0if6j6XlHXt45eumk34="
     - secure: "p8RZuB9RJdBMxvNYPXYH6UCgDHoLWj4SAUtrWGOLiJvqXwBTAPu7RwE961GV4x+E07HSTSsfMxN+92RPuikjT2yXl0Hyfjzp/S8dxgGAjHtUXGH1vV12eObF3YMA6MAPlw1DYWR0fQMtYm09yGEjU6Uf4QqZoT3pSaZzyYgYmRM69e2L8BtPP4Op4fpyM+tRsMWG0aeNu9Tv14HhUkaqN9fanDd9oCOzHBZh8GNNY9weDJOtm9BFIzIn/D4aY5BFAjRBnJSoOvB9XyE5BmI5EQ5bwRm/6YpP7eHNl0h+zKxt3MbtyxGENx6GQMa9Drq01GZQXBMnqgEHUHJmWGwjShf8Fq+tStVGGoWdh8tg7B+n8tsOzeWz9ThB4eGroAH7DeeMugKgSg3sXvSeJUFmMKDCsWmpoO57rBFk4E6SV200V5utlKNjrzQWOfR30s8rjt5wOfJI5ftcyzWyfSdGht/Nxoar7NsT/QiW75DOWONU5LDaAQPQQKYwcAk2h3iOGjbgLVYoEm/+bplraqaAbDcsJsqJTZqkl5pOjOjoFNZUJpXd2KpnF8LhrhTbkD+pZoU/N7LN4Kur10ZfqY1sw1iOXpE/siBL4X2sW+yEjc4vgpicIMNLjiJr2pEpb1EsFYvBZ27IAXFQbwlAqGlBGN0l3kkPwXjkSknbqoy5Tck="
    on_sucess: change
    on_failure: always
